@baseUrl = http://localhost:3002

POST {{baseUrl}}/database/find
Content-Type: application/json

{
		"databaseName": "items",
		"collectionName": "nfs",
		"filter": {}
}

###

POST {{baseUrl}}/database/findOne
Content-Type: application/json

{
		"databaseName": "items",
		"collectionName": "nfs",
		"filter": {}
}

###

POST {{baseUrl}}/database/insertOne
Content-Type: application/json

{
		"databaseName": "nfs",
		"collectionName": "index",
		"document": {
			"batata": "38"
		}
}

###

POST {{baseUrl}}/database/updateOne
Content-Type: application/json

{
		"databaseName": "nfs",
		"collectionName": "index",
		"filter": {
			"batata": "38"
		},
		"update": {
			"batata": 357
		}
}