name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      TZ: America/Sao_Paulo

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run linter
        run: npm run lint

      - name: Run unit tests
        run: npm test -- --run
        # Note: Only unit tests (Vitest) are run in CI.
        # Integration tests (Playwright) are for local development only.
        # Use 'npm run test:e2e' locally to run integration tests.
